Web/mobile controls (webrtc)
weave-game/weave pull request #78
Opened 2023-10-16 20:05 UTC by erikwessman

This is just to get it into main, still have to fix:

1. Dont hardcode URL to the remote signalling server
2. Change the string in WebInputSource's LeftInputString() and RightInputString() to something else
3. Dont show the QR and lobby code at the start screen immediately, only after press start (important!1!1!)
4. Add a method NotifyChangePlayerColor(string clientId, string newColor) to webrtc manager that notifies web clients of their color (so we can show it in mobile UI 🤪)

2023-10-16 20:07 UTC, erikwessman commented
Also look at this if you wanna know what tf going on
https://github.com/weave-game/signalling-server#readme

2023-10-16 20:52 UTC, theowiik requested changes
🌐 🌐 🌐 ☎️

2023-10-16 20:52 UTC, theowiik commented on weave/Menus/LobbyDemo.tscn
> +[gd_scene load_steps=3 format=3 uid="uid://suha7hqfnwef"]
Re-added, is this used?

2023-10-16 20:52 UTC, theowiik commented on weave/Scripts/InputSources/Lobby.cs
> +    private const int _lobbyCodeLength = 5;
namings

2023-10-16 20:52 UTC, theowiik commented on weave/Scripts/InputSources/Lobby.cs
> +            result[i] = allowedCharacters[rnd.Next(allowedCharacters.Length - 1)];
What if this code is taken 🤭 (probably not a concern for us, fix if you want to)

2023-10-16 20:52 UTC, theowiik commented on weave/Scripts/InputSources/WebInputSource.cs
> +    public string Id;
To properties (just add { get; set; })

2023-10-16 20:52 UTC, theowiik commented on weave/Scripts/Multiplayer/Manager.cs
> +public partial class Manager : Node
We should probably have a more descriptive name? Perhaps NetworkClientManager? or something like that

2023-10-16 20:52 UTC, theowiik commented on weave/Scripts/Multiplayer/Manager.cs
> +namespace Weave.Multiplayer;
Im thinking if we should rename this folder/namespace to something like Networking, as it is multiplayer but the other input sources are also forms of multiplayer

2023-10-16 20:52 UTC, theowiik commented on weave/Scripts/Multiplayer/Manager.cs
> +public partial class Manager : Node
Does it need to inherit from Node?

2023-10-16 20:52 UTC, theowiik commented on weave/Scripts/Multiplayer/Manager.cs
> +        foreach (var clientId in _clientConnections.Keys)
Hmm looks good 🥸🥸🥸yes 🥸🥸🥸

2023-10-16 20:52 UTC, theowiik commented on weave/Scripts/Utils/GDScriptHelper.cs
> +    public static ImageTexture GenerateQRCodeFromString(string str)
I mentioned this in the last PR, but perhaps ""removing"" the gdscript dependency with a IQrCodeGenerator

2023-10-16 20:52 UTC, theowiik commented
> Load solution '/home/runner/work/weave/weave/weave/Weave.sln' Done loading solution '/home/runner/work/weave/weave/weave/Weave.sln' Analyze solution '/home/runner/work/weave/weave/weave/Weave.sln' Analyze 'WeaveGame' 1/2 Scripts/MenuControllers/GameOverOverlay.cs(25,13): warning CS4014: Because this call is not awaited, execution of the current method continues before the call is completed. Consider applying the 'await' operator to the result of the call. Scripts/MenuControllers/StartScreen.cs(64,9): warning CS4014: Because this call is not awaited, execution of the current method continues before the call is completed. Consider applying the 'await' operator to the result of the call. Scripts/InputSources/IInputSource.cs(2,1): hidden CS8019: Unnecessary using directive. Scripts/InputSources/WebInputSource.cs(1,1): hidden CS8019: Unnecessary using directive. Scripts/MenuControllers/GameOverOverlay.cs(4,1): hidden CS8019: Unnecessary using directive. Analyze 'WeaveTests' 2/2 Done analyzing solution '/home/runner/work/weave/weave/weave/Weave.sln' in 00:07.98
> 
> 2 CS4014 Because this call is not awaited, execution of the current method continues before the call is completed 3 CS8019 Unnecessary using directive
> 
> 5 diagnostics found

Most of these can be fixed with: `roslynator fix .\Weave.sln --format`

2023-10-16 20:53 UTC, theowiik commented
> SonarCloud Quality Gate failed.    [![Quality Gate failed](https://camo.githubusercontent.com/4ea51c1f64ee3746f631653a02ab678ca6a3efb5f5cb474402faed2e3dcf90b5/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f5175616c6974794761746542616467652f6661696c65642d313670782e706e67)](https://sonarcloud.io/dashboard?id=weave-game_weave&pullRequest=78)
> 
> [![Bug](https://camo.githubusercontent.com/4c6102327f5a954f9c8acaf2e2714183157a9e41717b371b2cd585cf25057310/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f6275672d313670782e706e67)](https://sonarcloud.io/project/issues?id=weave-game_weave&pullRequest=78&resolved=false&types=BUG) [![C](https://camo.githubusercontent.com/57cf2cd81158730ed1dd8be1e93a41a2feb8b35dd75e5601402ba5f961f6ec18/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f432d313670782e706e67)](https://sonarcloud.io/project/issues?id=weave-game_weave&pullRequest=78&resolved=false&types=BUG) [3 Bugs](https://sonarcloud.io/project/issues?id=weave-game_weave&pullRequest=78&resolved=false&types=BUG) [![Vulnerability](https://camo.githubusercontent.com/3ba1ee49636ffc3427e38649a9f8a65ee392f28e8a662fcf96ce24cefbb520e9/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f76756c6e65726162696c6974792d313670782e706e67)](https://sonarcloud.io/project/issues?id=weave-game_weave&pullRequest=78&resolved=false&types=VULNERABILITY) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/issues?id=weave-game_weave&pullRequest=78&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=weave-game_weave&pullRequest=78&resolved=false&types=VULNERABILITY) [![Security Hotspot](https://camo.githubusercontent.com/fb735cbe76f8d5e1679c76ce83b740ceb1eaf62de4f7bf88623dc9953261aff7/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f73656375726974795f686f7473706f742d313670782e706e67)](https://sonarcloud.io/project/security_hotspots?id=weave-game_weave&pullRequest=78&resolved=false&types=SECURITY_HOTSPOT) [![E](https://camo.githubusercontent.com/ca3e5c9e7ad5fd04244d2d793976efbe479a024b145a815384556548a9884b5f/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f452d313670782e706e67)](https://sonarcloud.io/project/security_hotspots?id=weave-game_weave&pullRequest=78&resolved=false&types=SECURITY_HOTSPOT) [1 Security Hotspot](https://sonarcloud.io/project/security_hotspots?id=weave-game_weave&pullRequest=78&resolved=false&types=SECURITY_HOTSPOT) [![Code Smell](https://camo.githubusercontent.com/8fe18b2dfb6f7d4e44582f281b29f617eb5ae07c248d2002ca586e91da219212/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f636f64655f736d656c6c2d313670782e706e67)](https://sonarcloud.io/project/issues?id=weave-game_weave&pullRequest=78&resolved=false&types=CODE_SMELL) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/issues?id=weave-game_weave&pullRequest=78&resolved=false&types=CODE_SMELL) [11 Code Smells](https://sonarcloud.io/project/issues?id=weave-game_weave&pullRequest=78&resolved=false&types=CODE_SMELL)
> 
> [![0.0%](https://camo.githubusercontent.com/3f04cff3eeef8477afe696ae55c570cbb6ed02f16152497c14251828329a3e91/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f436f76657261676543686172742f302d313670782e706e67)](https://sonarcloud.io/component_measures?id=weave-game_weave&pullRequest=78&metric=new_coverage&view=list) [0.0% Coverage](https://sonarcloud.io/component_measures?id=weave-game_weave&pullRequest=78&metric=new_coverage&view=list) [![0.0%](https://camo.githubusercontent.com/8047c63e1f9ed03f63001e1eadce4676bade3e0f83ec690a9c625287796248a6/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f4475706c69636174696f6e732f332d313670782e706e67)](https://sonarcloud.io/component_measures?id=weave-game_weave&pullRequest=78&metric=new_duplicated_lines_density&view=list) [0.0% Duplication](https://sonarcloud.io/component_measures?id=weave-game_weave&pullRequest=78&metric=new_duplicated_lines_density&view=list)
> 
> ![idea](https://camo.githubusercontent.com/00150338e138e454e357462ed3d9cfceaf338ca50ccadcc1f3a75ad6a0e2aab2/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f6c696768745f62756c622d313670782e706e67) Catch issues before they fail your Quality Gate with our IDE extension ![sonarlint](https://camo.githubusercontent.com/e4a8f808c72d84f231c1400ce7f2c77a09afe3eadb6bde9ad2c208a46735d320/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f736f6e61726c696e742d313670782e706e67) [SonarLint](https://www.sonarsource.com/products/sonarlint/features/connected-mode/?referrer=sonarcloud-welcome)

We can take a look at these at the next PR

2023-10-17 09:09 UTC, elias-carlson approved these changes
LGTM

2023-10-17 09:44 UTC, elias-carlson approved these changes
still LGTM

2023-10-17 11:14 UTC, theowiik approved these changes

2023-10-17 11:14 UTC, merged